### ISSUE TITLE
如何实现断点续传上传文件?

### ISSUE THREAD

**Issue by com314159** [alibaba/alicloud-ios-demo#10]
我使用OSSTask * putTask = [client putObject:put];经过测试是无法断点续传的? 难道一定要使用resumableUploadFile?

**Comment by xuyecan** [comment]
目前要实现断点续传有两种方式：
1. 通过自己编程组合分块上传的几个独立接口来实现；
2. 通过已经封装分块上传接口的为了兼容旧版本用法的接口`resumableUploadFile`来实现；

**Comment by xuyecan** [comment]
分块上传相关用法参考工程文档：https://github.com/aliyun/aliyun-oss-ios-sdk

**Comment by com314159** [comment]
put 方法设置range理论上也是可以断点续传吧? 为什么不提供一下这个方法, 虽然这种不如分块好. 

1. 先请求服务器查看文件已经上传了多大
2. 在put时, 传入range参数

理论上应该可以的.
但是查看你们的SDK, 发现已经屏蔽了, 没有给Range方法.

**Comment by xuyecan** [comment]
不行的，上传没有range设置，可以参考：https://docs.aliyun.com/#/pub/oss/api-reference/object&PutObject。put方法，server不会保存session状态，所以该次session断掉之后，就需要重新上传。

**Comment by com314159** [comment]
我在这里提了很多Bug, 你们麻烦修复一下. https://github.com/aliyun/aliyun-oss-ios-sdk  的issue

**Comment by xuyecan** [comment]
好的，已经在跟进。

**Comment by xuyecan** [comment]
好的，已经在跟进。

**Comment by xuyecan** [comment]
非常感谢您的反馈，如果您有什么自己的想法，也欢迎提交PR。
