### ISSUE TITLE
完成回调错误

### ISSUE THREAD

**Issue by com314159** [alibaba/alicloud-ios-demo#11]
原代码
    
            if (task.error) {
            onComplete(NO, task.error);
        } else {
            onComplete(YES, nil);
        }

如果这个task是取消的, 是没有错误的, 这样写是有Bug的

**Comment by com314159** [comment]
应该是判断(task.completed == YES && task.faulted == NO)

**Comment by com314159** [comment]
应该是判断:  completed = YES; cancelled = NO; faulted = NO

**Comment by xuyecan** [comment]
已在 https://github.com/aliyun/aliyun-oss-ios-sdk/issues/10 中处理。
