### ISSUE TITLE
获取bucket子文件夹列表时有bug。

### ISSUE THREAD

**Issue by limaomt** [alibaba/alicloud-ios-demo#13]
获取文件列表时OSSGetBucketRequest getBucket.delimiter = @"/";
查询一个子文件夹时候，如果该文件夹里面只有一个子文件夹时，会爆下面错误，获取没有回调。

-[NSTaggedPointerString objectForKey:]: unrecognized selector sent to instance 0xa007869666572506

**Comment by xuyecan** [comment]
https://github.com/aliyun/aliyun-oss-ios-sdk 

最新代码已经修复这个问题 [#380613](https://github.com/aliyun/aliyun-oss-ios-sdk/commit/3806136aaa4eca3547b64e6c3aa352d4ada707f4)，重新clone project调用`./buildFramework.sh`打包即可。
